# Generated by Django 4.0.4 on 2022-05-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_user_task_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(default='ee286bde-2', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=9),
        ),
    ]
