# Generated by Django 4.0.4 on 2022-05-08 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_slug_alter_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=uuid.UUID('d47760fd-b612-47d0-8dc3-918cd1325182'), max_length=30),
        ),
    ]
