# Generated by Django 4.0.4 on 2022-05-08 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e1dd5b59-86ff-4c17-8ecf-8c7fcf647641'), max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='d53dc498-0cca-4636-aa80-7302167c5a4e', max_length=200, null=True),
        ),
    ]
