# Generated by Django 4.0.4 on 2022-05-08 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_task_slug_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5a6470f4-2356-4b95-b9b7-b63a8e0c5004'), max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
