# Generated by Django 4.0.4 on 2022-05-08 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_task_slug_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=uuid.UUID('42fc8a17-0c75-4a43-92fc-022e007b708c'), max_length=30),
        ),
    ]
