# Generated by Django 4.0.4 on 2022-05-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_rename_title_task_name_rename_state_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='state',
        ),
    ]
